famous_people/urls.py
from django.urls import path
from .views import *

app_name = "famous_people"

urlpatterns = [
    path('', HomePageView.as_view(), name="home_url"),
    path('portal/', PortalUploadData.as_view(), name="portal_upload_data_url"),
    path('<slug:title_slug>-facts/',PostPageView.as_view(),name='post_url'),
]

polynomials_project/urls.py
from django.contrib import admin
from django.urls import include, path
from difference_between.sitemaps import *
from django.contrib.sitemaps.views import sitemap,index
from polynomials.views import aboutus,contactus,disclaimer,privacy_policy
from webstory.webstory_sitemap import *;
from django.views.static import serve
from django.conf import settings
from polynomials.Sitemaps import *;
sitemaps = {
    'Category-sitemap': Category_Sitemap,
   'Difference-Between-sitemap':Differ_Sitemap,
   'polynomials-addition-sitemap':poly_add_Sitemap,
     'polynomials-subtraction-sitemap':poly_sub_Sitemap,
     'polynomials-multiplication-sitemap':poly_mul_Sitemap,
     'polynomials-division-sitemap':poly_div_Sitemap,
     'is-expression-polynomial-sitemap':check_poly_Sitemap,
     'degree-of-polynomials-sitemap':degree_poly_Sitemap,
     'polynomial-in-ascending-order-sitemap':ascding_poly_Sitemap,
     'polynomial-in-descending-order-sitemap':descding_poly_Sitemap,
     'leading-polynomials-sitemap':leading_poly_Sitemap,
     'polynomials-factors-sitemap':fact_poly_Sitemap,
     'polynomials-gcf-sitemap':gcf_poly_Sitemap,
     'polynomials-gcf-factors-sitemap':gcf_fact_Sitemap,
     'polynomials-lcm-sitemap':poly_lcm_Sitemap,
     'prime-polynomials-sitemap':poly_prime_Sitemap,
     'polynomials-factor-as-adiition-difference-of-cube-sitemap':poly_fact_cube_Sitemap,
     'polynomials-factor-as-difference-of-square-sitemap':poly_fact_sqr_Sitemap,
     'binomial-expansion-sitemap':binom_expn_Sitemap,
     'polynomials-factor-over-complex-sitemap':fact_complex_Sitemap,
     'polynomials-root-sitemap':poly_root_Sitemap,
     'polynomial-remainder-theorm-sitemap':poly_remainder_Sitemap,
   'entertainment-sitemap':EntertainmentView,
   'covid-sitemap':CovidView,
   'celeb-sitemap':CelebView,
   'food-sitemap':FoodView,
   'fitness-sitemap':FitnessView,
   'fashion-sitemap':FashionView,
   'health-sitemap':HealthView,
   'beauty-sitemap':BeautyView,
   
   'sports-sitemap':SportsView,
   'gaming-sitemap':GamingView,
   'tech-sitemap':TechView,
   'latest-sitemap':LatestView,
   

}

urlpatterns = [
    path('about-us/',aboutus, name='about-us'),
    path('contact-us/',contactus, name='contact-us'),
    path('disclaimer/',disclaimer, name='disclaimer'),
    path('privacy-policy/',privacy_policy, name='privacy-policy'),
    path('admin/', admin.site.urls),
    path('', include('polynomials.urls')),
    path('web-stories/', include('webstory.urls')),
    path('difference-between/', include('difference_between.urls')),
    path('famous-people/', include('famous_people.urls')),
   
    path('sitemap.xml', index, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.index'),
    path('<section>.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

handler404 = 'webstory.views.handler404'

webstory/urls.py
from django.urls import path,include
from .views import *

urlpatterns = [
    path('',homepage, name='home'),
    path('humor/',humor,name='humor'),
    path('celeb/',celeb,name='celeb'),
    path('beauty/',beauty,name='beauty'),
    path('latest/',latest,name='latest'),
    path('covid/',covid,name='covid'),
    path('food/',food,name='food'),
    path('gaming/',gaming,name="gaming"),
    path('entertainment/',entertainment,name='entertainment'),

    path('travel/',travel,name='travel'),
    path('tech/',tech,name='tech'),
    path('wellness/',wellness,name='wellness'),
    path('fashion/',fashion,name='fashion'),
    path('health/',health,name='health'),
    path('sports/',sports,name='sports'),
    path('fitness/',fitness,name='fitness'),

    path('<str:category>/<str:story>/',webstories,name='webstories')
]
import webstory.jobs  # NOQA @isort:skip
import logging
logging.basicConfig(level="DEBUG")

famous_people/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField

class FamousPeople(models.Model):
    title = models.CharField(max_length=300, unique=True)
    slug = models.SlugField(max_length=300, unique=True, blank=True)
    subtitle = models.CharField(max_length=500,null=True,blank=True)
    meta_description = models.CharField(max_length=500,null=True,blank=True)
    jump_links = models.TextField(default="[]")
    birthday_highlights = models.TextField(default="{}")
    facts = models.TextField(default="{}")
    content = RichTextField()
    image = models.CharField(max_length=255,null=True,blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(FamousPeople, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

famous_people/views.py
import json
from django.http import Http404
from django.views.generic import TemplateView,ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .utils import saveDataInDB
from .models import *
from django.conf import settings
import os


class PortalUploadData(LoginRequiredMixin, TemplateView):
    login_url = "/admin/login/"
    template_name = "famous_people/portal_upload_data.html"
    extra_context = {}

    def get(self, request, *args, **kwargs):
        self.extra_context["msg"] = ""
        self.extra_context["famous_random_peoples_header"] = FamousPeople.objects.all().order_by("?")[:5]
        self.extra_context["famous_random_peoples_footer"] = FamousPeople.objects.all().order_by("?")[:15]
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        json_file = request.FILES.get("json_file")
        try:
            if not json_file:
                json_file = open(os.path.join(settings.MEDIA_ROOT,"temp","famous_people.json"),encoding="utf-8")
            data = json.load(json_file)
            res = saveDataInDB(data,json_file.name)
            msg = f"<span style='color:green;'>Success : {res}</span>"
        except Exception as e:
            msg = f"<span style='color:red;'>Error : {e}</span>"
        self.extra_context["msg"] = msg
        return super().get(request, *args, **kwargs)


class HomePageView(ListView):
    template_name = "famous_people/homepage.html"
    extra_context = {}
    paginate_by = 100

    def get_queryset(self):
        return FamousPeople.objects.all().order_by("-id")

    def get(self, *args, **kwargs):
        self.extra_context["famous_random_peoples_header"] = FamousPeople.objects.all().order_by("?")[:5]
        self.extra_context["famous_random_peoples_footer"] = FamousPeople.objects.all().order_by("?")[:15]
        return super().get(*args, **kwargs)
    

class PostPageView(TemplateView):
    template_name = "famous_people/post_page.html"
    extra_context = {}

    def get(self, *args, **kwargs):
        title_slug = self.kwargs.get("title_slug")
        famous_people_obj = FamousPeople.objects.filter(slug=title_slug)
        if famous_people_obj:
            famous_people_obj = famous_people_obj.first()
            self.extra_context["famous_people_obj"] = famous_people_obj
            self.extra_context["jump_links"] = json.loads(famous_people_obj.jump_links)
            self.extra_context["birthday_highlights"] = json.loads(famous_people_obj.birthday_highlights)
            self.extra_context["facts"] = json.loads(famous_people_obj.facts)
            self.extra_context["famous_random_peoples_header"] = FamousPeople.objects.all().order_by("?")[:5]
            self.extra_context["famous_random_peoples_footer"] = FamousPeople.objects.all().order_by("?")[:15]
            return super().get(*args, **kwargs)
        else:
            raise Http404

templates/famous_people/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block head %} {% endblock head %}

  <!-- Online Calculator Guru Site Fevicon -->
  <link rel="shortcut icon" href="https://onlinecalculator.guru/static/images/logo/Online-Calculator-Guru-Fevicon.png"
    type="icon">

  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
  <!-- MDB -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.2/mdb.min.css" rel="stylesheet" />
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <!-- Custom CSS -->
  <link rel="stylesheet" href="https://onlinecalculator.guru/static/style.css">
  <link rel="stylesheet" href="{% static 'famous_people_style.css' %}">

  <!-- Bootstrap Jquery, Google APIS -->
  <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet" />
  <script src="https://use.fontawesome.com/4083775673.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>

  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-169198200-4"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() {
      dataLayer.push(arguments);
    }
    gtag("js", new Date());

    gtag("config", "UA-169198200-4");
  </script>
  <script data-ad-client="ca-pub-4620359738364721" async
    src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
</head>


<body>

  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #1a237e;">
    <div class="container-fluid">
      <a class="navbar-brand lead font-weight-bold" href="{% url 'famous_people:home_url' %}">Famous People</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler"
        aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggler">
        <ul class="navbar-nav ml-auto">
          {% for people in famous_random_peoples_header %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'famous_people:post_url' people.slug %}">{{people.title}}</a>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </nav>

  {% block body %}{% endblock body %}
  <br>

  <!-- Footer -->
  <footer class="text-center text-lg-start text-white" style="background-color: #1a237e;">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4"
      style="background-color: rgba(0, 0, 0, 0.050);">
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>Get connected with us on social networks</span>
      </div>
      <!-- Left -->

      <!-- Right -->
      <div>
        <a target="_blank" href="https://www.facebook.com/Factor-Polynomials-102151955136428"
          class="me-4 text-reset text-decoration-none">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a target="_blank" href="https://twitter.com/factorpolynomil" class="me-4 text-reset text-decoration-none">
          <i class="fab fa-twitter"></i>
        </a>
        <a target="_blank" href="https://www.linkedin.com/in/factorpolynomials/"
          class="me-4 text-reset text-decoration-none">
          <i class="fab fa-linkedin"></i>
        </a>
        <a target="_blank" href="https://www.youtube.com/channel/UCFkMv7w89Dqc0XukZUcWsFA/"
          class="me-4 text-reset text-decoration-none">
          <i class="fab fa-youtube"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <br>

    <!-- Section: Links -->
    <section class="container" style="background-color: #1a237e;">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-md-4 mb-4 mb-md-0">
          <h5 class="text-capitalize">Favorite Calculators</h5>

          <ul class="list-unstyled mb-0">
            <li><a href="https://onlinecalculator.guru/math-calculator/" title="Maths Calculator">Maths Calculator</a>
            </li>
            <li><a href="https://physicscalc.com/" title="Physics Calculator">Physics Calculator</a></li>
            <li><a href="https://chemistrycalc.com/" title="Chemistry Calculator">Chemistry Calculator</a></li>
            <li><a href="https://lcmgcf.com/" title="LCM and GCF Calculator">LCM and GCF Calculator</a></li>
            <li><a href="https://multiplyfractions.com/" title="Fractions Calculator">Fractions Calculator</a></li>
            <li><a href="https://factorpolynomials.com/" title="Polynomials Calculator">Polynomials Calculator</a></li>
            <li><a href="https://percentagecalculator.guru/" title="Percentage Calculator">Percentage Calculator</a>
            </li>
            <li><a href="https://areavolumecalculator.com/" title="Area and Volume Calculator">Area and Volume
                Calculator</a></li>
            <li><a href="https://linearequationscalculator.com/" title="Linear Equations Calculator">Linear Equations
                Calculator</a></li>
            <li><a href="https://roundingcalculator.guru/" title="Rounding Calculator">Rounding Calculator</a></li>
            <li><a href="https://statisticscalculators.net/" title="Statistics Calculator">Statistics Calculator</a>
            </li>
            <li><a href="https://hcflcm.com/" title="HCF and LCM Calculator">HCF and LCM Calculator</a></li>
            <li><a href="https://sequencecalculators.com/" title="Sequences Calculator">Sequences Calculator</a></li>
            <li><a href="https://probabilitycalculator.guru/" title="Probability Calculator">Probability Calculator</a>
            </li>
            <li><a href="https://arithmeticcalculator.com/" title="Arithmetic Calculator">Arithmetic Calculator</a></li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4 mb-md-0">
          <h5 class="text-capitalize">Most Popular People</h5>

          <ul class="list-unstyled mb-0">
            {% for people in famous_random_peoples_footer %}
            <li>
              <a href="{% url 'famous_people:post_url' people.slug %}">{{people.title}}</a>
            </li>
            {% endfor %}
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4 mb-md-0">
          <h5 class="text-capitalize">Company</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a href="/about-us/">About US</a>
            </li>
            <li>
              <a href="/contact-us/">Contact US</a>
            </li>
            <li>
              <a href="/privacy-policy/">Privacy Policy</a>
            </li>
            <li>
              <a href="/disclaimer/">Disclaimer</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->
    </section>
    <!-- Section: Links -->

    <br>

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2022 Copyright:
      <a class="text-white" href="https://factorpolynomials.com/">Factorpolynomials.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

  {% block script %} {% endblock script %}
</body>

</html>

templates/famous_people/homepage.html
{% extends 'famous_people/base.html' %}
{% load static %}
{% load custom_tags %}

{% block head %}
<title>Famous People Facts - Factorpolynomials.com</title>
<meta name="description" content="Happy Birthday to you! We've got endless birthday ideas for all ages, you need not look any further. From DIY decorations, to at-home party inspiration and more cake ideas than you can shake a stick at, we've got it all.">

<!-- Open Graph Meta -->
<meta property="og:site_name" content="HowToGeeks">
<meta property="og:url" content="{{request.build_absolute_uri}}">
<meta property="og:title" content="Famous People Facts - Factorpolynomials.com">
<meta property="og:description" content="Happy Birthday to you! We've got endless birthday ideas for all ages, you need not look any further. From DIY decorations, to at-home party inspiration and more cake ideas than you can shake a stick at, we've got it all.">
<meta property="og:type" content="website">
<meta property="og:image" content="https://onlinecalculator.guru/static/images/logo/Online-Calculator-Guru-Fevicon.png">

<!-- Twitter Meta -->
<meta name="twitter:card" content="summary">
<meta name="twitter:url" content="{{request.build_absolute_uri}}">
<meta name="twitter:title" content="Famous People Facts - Factorpolynomials.com">
<meta name="twitter:description" content="Happy Birthday to you! We've got endless birthday ideas for all ages, you need not look any further. From DIY decorations, to at-home party inspiration and more cake ideas than you can shake a stick at, we've got it all.">
<meta name="twitter:image"
    content="https://onlinecalculator.guru/static/images/logo/Online-Calculator-Guru-Fevicon.png">
{% endblock head %}

{% block body %}

<div class="container-fluid px-5">
    <br>
    <div class="row justify-content-center">
        {% for people in object_list %}
        <div class="card m-1" style="width: 18rem;">
            <a href="{% url 'famous_people:post_url' people.slug %}" style="color: black;text-decoration: none;">
                <img src="{{people.image}}" class="card-img-top" style="max-height: 275px;" alt="{{people.title}}" />
                <div class="card-body" style="padding: 5px !important;">
                    <h3 class="card-title mb-0">{{people.title}}</h3>
                    <p class="card-test text-muted mb-0">
                        {% get_people_metadata people %}
                    </p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>


<br><br>
{% if is_paginated %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center" style="list-style-type: none !important;">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                    <span aria-hidden="true">&laquo; Prev</span>
                </a>
            </li>
            {% if page_obj.number|add:"-2" != 0 %}
            <li class="page-item"><a class="page-link"
                    href="?page={{page_obj.number|add:'-2'}}">{{page_obj.number|add:"-2"}}</a></li>
            {% endif %}
            <li class="page-item"><a class="page-link"
                    href="?page={{page_obj.previous_page_number}}">{{page_obj.previous_page_number}}</a></li>
        {% endif %}

        <li class="page-item active"><a class="page-link" href="?page={{page_obj.number}}">{{page_obj.number}}</a></li>

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link"
                    href="?page={{page_obj.next_page_number}}">{{page_obj.next_page_number}}</a></li>
            {% if page_obj.number|add:"2" != 0 and page_obj.number|add:"2" <= page_obj.paginator.num_pages %} <li
                class="page-item"><a class="page-link"
                    href="?page={{page_obj.number|add:'2'}}">{{page_obj.number|add:"2"}}</a></li>
            {% endif %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                        <span aria-hidden="true">Next &raquo;</span>
                    </a>
                </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

{% endblock body %}

{% block script %}
{% endblock script %}

templates/famous_people/portal_upload_data.html
{% extends 'famous_people/base.html' %}
{% load static %}

{% block head %}
<title>Portal - Upload Data - Factorpolynomials.com</title>
<meta name="description" content="Portal Upload Data.">

<!-- Open Graph Meta -->
<meta property="og:site_name" content="HowToGeeks">
<meta property="og:url" content="{{request.build_absolute_uri}}">
<meta property="og:title" content="Portal - Upload Data - Factorpolynomials.com">
<meta property="og:description" content="Portal Upload Data.">
<meta property="og:type" content="website">
<meta property="og:image" content="https://onlinecalculator.guru/static/images/logo/Online-Calculator-Guru-Fevicon.png">

<!-- Twitter Meta -->
<meta name="twitter:card" content="summary">
<meta name="twitter:url" content="{{request.build_absolute_uri}}">
<meta name="twitter:title" content="Portal - Upload Data - Factorpolynomials.com">
<meta name="twitter:description" content="Portal Upload Data.">
<meta name="twitter:image" content="https://onlinecalculator.guru/static/images/logo/Online-Calculator-Guru-Fevicon.png">
{% endblock head %}

{% block body %}
<br>
<div class="container text-right">
    <a class="btn btn-primary btn-sm" href="/admin/logout/" role="button">Logout</a>
</div>
<div class="container col-md-4 text-center">
    <br>
    {% if msg %}
    <div class="alert alert-info" role="alert">
        <strong>{{msg|safe}}</strong>
    </div>
    {% endif %}
    <h3>Upload Data For Famous People</h3>
    <form method="post" enctype="multipart/form-data" onsubmit="$('.btn.btn-success').attr('disabled','');">
        {% csrf_token %}
        <input type="file" style="padding: 100px" name="json_file" class="form-control mt-2" accept=".json">
        <span class="text-muted small d-block text-left mb-3">For large json data kindly upload file from server in temp dir and click upload directly</span>
        <button class="btn btn-info w-100" type="submit">Upload</button>
    </form>
    <br>    <br>    <br>
</div>
{% endblock body %}

{% block script %}
{% endblock script %}

templates/famous_people/post_page.html
{% extends 'famous_people/base.html' %}
{% load static %}

{% block head %}
<title>{{famous_people_obj.title}} - Famous People Facts - Factorpolynomials.com</title>
<meta name="description" content="{{famous_people_obj.meta_description}}">

<!-- Open Graph Meta -->
<meta property="og:site_name" content="HowToGeeks">
<meta property="og:url" content="{{request.build_absolute_uri}}">
<meta property="og:title" content="{{famous_people_obj.title}} - Famous People Facts - Factorpolynomials.com">
<meta property="og:description" content="{{famous_people_obj.meta_description}}">
<meta property="og:type" content="website">
<meta property="og:image" content="{{request.scheme}}://{{request.get_host}}{{famous_people_obj.image}}">

<!-- Twitter Meta -->
<meta name="twitter:card" content="summary">
<meta name="twitter:url" content="{{request.build_absolute_uri}}">
<meta name="twitter:title" content="{{famous_people_obj.title}} - Famous People Facts - Factorpolynomials.com">
<meta name="twitter:description" content="{{famous_people_obj.meta_description}}">
<meta name="twitter:image" content="{{request.scheme}}://{{request.get_host}}{{famous_people_obj.image}}">
{% endblock head %}

{% block body %}
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb bg-transparent my-2" style="font-size: larger;">
            <li class="breadcrumb-item"><a href="{% url 'famous_people:home_url' %}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{famous_people_obj.title}}</li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-lg-8">
            <h1>
                {{famous_people_obj.title}}
                <br>
                {{famous_people_obj.subtitle}}
            </h1>
            <hr>
            <ul class="jump-links">
                {% for jump_link in jump_links %}
                <li><a href="#{{jump_link|slugify}}">{{jump_link}}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-lg-4 mt-auto mb-auto">
            <img src="{{famous_people_obj.image}}" alt="{{famous_people_obj.title}}">
        </div>
    </div>
    <br>


    <div id="birthday-highlights" class="card bg-light mb-3">
        <div class="card-header text-dark" style="background-color: rgba(211, 211, 211, 0.216);">
            <h2>{{famous_people_obj.title}}'s Birthday Highlights</h2>
        </div>
        <div class="card-body">
            <div class="row">
                {% for items in birthday_highlights.items %}
                <div class="col-md-4 mb-4" style="font-size: larger;">
                    {% if items.0 == "Age" %}
                        <strong>{{famous_people_obj.title}}'s {{items.0}}</strong>
                    {% else %}
                        <strong>{{items.0}}</strong>
                    {% endif %}
                    <br>
                    <span>{{items.1}}</span>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <br>


    <div id="facts" class="card bg-light mb-3">
        <div class="card-header text-dark" style="background-color: rgba(211, 211, 211, 0.216);">
            <h2>{{famous_people_obj.title}} Facts</h2>
        </div>
        <div class="card-body">
            <div class="row">
                {% for items in facts.items %}
                <div class="col-md-4 mb-4" style="font-size: larger;">
                    <strong>{{items.0}}</strong>
                    <br>
                    <span>{{items.1}}</span>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <br>

    <div id="post-content" class="container col-md-10 ml-0">
        {{famous_people_obj.content|safe}}
    </div>
    <br>
</div>
{% endblock body %}

{% block script %}
<script>
    $(document).ready(function () {
        $("#post-content h2").before("<br/>");
        $(".mv-ad-box").remove();
    });
</script>
{% endblock script %}